/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/root-router/wrangler.jsonc --include-runtime=false apps/root-router/worker-configuration.d.ts` (hash: f16c8032cf7e2f6ee24cf4e4bcf4d67f)
interface __BaseEnv_Env {
	PORTAL: Fetcher /* 00ai-portal-origin */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
