/**
 * `Env` is generated by `wrangler types`. Secret names are intentionally not
 * present in wrangler.jsonc, so they are added as an intersection without
 * re-declaring any platform binding.
 */
export type RuntimeEnv = Env & {
  readonly YOUTH_POLICY_API_KEY?: string;
  readonly YOUTH_POLICY_LEGACY_ENABLED?: string;
  readonly LAW_API_OC?: string;
  readonly SYNC_SECRET?: string;
};
