/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 989ab2e9ecb59afb3e83766edf5d2adc)
interface __BaseEnv_Env {
	DB: D1Database;
	MCP_RATE_LIMITER: RateLimit;
	YOUTH_POLICY_API_BASE_URL: "https://www.youthcenter.go.kr";
	YOUTH_POLICY_API_PATH: "/go/ythip/getPlcy";
	YOUTH_POLICY_API_FORMAT: "json";
	YOUTH_POLICY_MAX_PAGES: "100";
	LAW_API_BASE_URL: "https://www.law.go.kr";
	KOSIS_MCP_URL: "https://mcp.gomdori.app/stats";
	MCP_PUBLIC_BASE_URL: "https://mcp.00ai.kr/youth";
	MCP_ALLOWED_HOSTS: "mcp.00ai.kr,localhost,127.0.0.1";
	MCP_ALLOWED_ORIGINS: "https://mcp.00ai.kr,http://localhost:5173,http://localhost:6274";
	SYNC_CRON_KST: "30 3 * * *";
	POLICY_STORAGE_BACKEND: "d1";
	TZ: "Asia/Seoul";
	POLICY_STORE_DO: DurableObjectNamespace<import("./src/index").YouthPolicyStore>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "YouthPolicyStore";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "YOUTH_POLICY_API_BASE_URL" | "YOUTH_POLICY_API_PATH" | "YOUTH_POLICY_API_FORMAT" | "YOUTH_POLICY_MAX_PAGES" | "LAW_API_BASE_URL" | "KOSIS_MCP_URL" | "MCP_PUBLIC_BASE_URL" | "MCP_ALLOWED_HOSTS" | "MCP_ALLOWED_ORIGINS" | "SYNC_CRON_KST" | "POLICY_STORAGE_BACKEND" | "TZ">> {}
}
